export const EVENT_TYPES = {
  LESSON: 'EVENT_TYPES.LESSON',
  PRACTICE: 'EVENT_TYPES.PRACTICE',
  MASTERCLASS: 'EVENT_TYPES.MASTERCLASS',
  PERFORMANCE: 'EVENT_TYPES.PERFORMANCE',
  THOUGHT: 'EVENT_TYPES.THOUGHT',
  OTHER: 'EVENT_TYPES.OTHER',
};

export const PERFORMANCE_TYPES = {
  CONCERT: 'PERFORMANCE_TYPES.CONCERT',
  OPERA: 'PERFORMANCE_TYPES.OPERA',
  RECITAL: 'PERFORMANCE_TYPES.RECITAL',
  COMPETITION: 'PERFORMANCE_TYPES.COMPETITION',
  AUDITION: 'PERFORMANCE_TYPES.AUDITION',
};

export const ITEM_TYPES = {
  PIECE: 'ITEM_TYPES.PIECE',
  EXERCISE: 'ITEM_TYPES.EXERCISE',
  THOUGHT: 'ITEM_TYPES.THOUGHT',
  PHYSICAL_EXERCISE: 'ITEM_TYPES.PHYSICAL_EXERCISE',
  GENERAL: 'ITEM_TYPES.GENERAL',
  OTHER: 'ITEM_TYPES.OTHER',
};

export const NOTE_TYPES = {
  TECHNICAL: 'NOTE_TYPES.TECHNICAL',
  INTERPRETATIONAL: 'NOTE_TYPES.INTERPRETATIONAL',
  GENERAL: 'NOTE_TYPES.GENERAL',
};
