export const EVENT_TYPES = {
  LESSON: 'EVENT_TYPES.LESSON',
  PRACTICE: 'EVENT_TYPES.PRACTICE',
  MASTERCLASS: 'EVENT_TYPES.MASTERCLASS',
  CONCERT: 'EVENT_TYPES.CONCERT',
  OPERA: 'EVENT_TYPES.OPERA',
  RECITAL: 'EVENT_TYPES.RECITAL',
  OTHER: 'EVENT_TYPES.OTHER',
};

export const ITEM_TYPES = {
  PIECE: 'ITEM_TYPES.PIECE',
  EXERCISE: 'ITEM_TYPES.EXERCISE',
  THOUGHT: 'ITEM_TYPES.THOUGHT',
  PHYSICAL_EXERCISE: 'ITEM_TYPES.PHYSICAL_EXERCISE',
  GENERAL: 'ITEM_TYPES.GENERAL',
  OTHER: 'ITEM_TYPES.OTHER',
};
